### PR TITLE
Added octal specifier to archive_entry fields to prevent Python 3 errors...

### PR DESCRIPTION
**Pull request by bovee**
Leading zeros throw a SyntaxError in my version of Python 3, so fixed that so `import libarchive.public` no longer fails.

https://www.python.org/dev/peps/pep-3127/#removal-of-old-octal-syntax

### CODE REVIEW

**Comment by jonathanslenders** [comment]
@dsoprea Any way of merging this and publishing it to Pypi? It should be backwards compatible.
Thanks!

**Comment by socketpair** [comment]
PING

**Comment by dsoprea** [comment]
Merged. Thanks for submitting and sorry for the delay.

**Comment by socketpair** [comment]
Anyway, python3 will not work with this. Problems: signed crc32, unicode constants `PK...` and so on

**Pull request merged**
